version: '3'

services:
  app:
      build: 
        context: ./
      image: joaoluizcadore/domain-seller-app
      container_name: app
      networks:
        - ds_network
      tty: true
      
  nginx: 
      depends_on:
        - app
      build:
        context: ./nginx
      container_name: nginx
      image: joaoluizcadore/nginx-ds
      tty: true
      ports:
        - "80:80"
      networks:
        - ds_network
networks:
  ds_network:
    driver: bridge